name: bmi_health_checker

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.2.0+0


environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  wheel_slider: ^1.2.2
  share_plus: ^10.1.4
  shared_preferences: ^2.3.5
  fl_chart: ^0.69.2
  google_mobile_ads: ^5.2.0
  connectivity_plus: ^6.1.2
  url_launcher: ^6.3.1
  flutter_slider_drawer: ^2.1.3
  flutter_exit_app: ^1.1.4
  get: ^4.6.6
  package_info_plus: ^8.1.3
  font_awesome_flutter: ^10.8.0
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  flutter_screenutil: ^5.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mockito: ^5.4.5
  build_runner: ^2.4.14


  flutter_lints: ^5.0.0
  riverpod_generator: ^2.6.4

flutter:

  uses-material-design: true

 
  fonts:
     - family: Poppins
       fonts:
         - asset: lib/fonts/Poppins-SemiBold.ttf

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
