name: bmi_health_checker
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  wheel_slider: ^1.2.1
  share_plus: ^10.1.2
  shared_preferences: ^2.3.3
  fl_chart: ^0.69.2
  google_mobile_ads: ^5.2.0
  connectivity_plus: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

 
  fonts:
     - family: Poppins
       fonts:
         - asset: lib/fonts/Poppins-SemiBold.ttf

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
